// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_
void rcpp_hello_();
RcppExport SEXP _Romp_rcpp_hello_() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_hello_();
    return R_NilValue;
END_RCPP
}
// rcpp_sum_
double rcpp_sum_(Rcpp::NumericVector x);
RcppExport SEXP _Romp_rcpp_sum_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sum_(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sweep_
Rcpp::NumericMatrix rcpp_sweep_(Rcpp::NumericMatrix x, Rcpp::NumericVector vec);
RcppExport SEXP _Romp_rcpp_sweep_(SEXP xSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sweep_(x, vec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_primesbelow_
int rcpp_primesbelow_(const int n);
RcppExport SEXP _Romp_rcpp_primesbelow_(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_primesbelow_(n));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP c_hello();
RcppExport SEXP c_primesbelow(SEXP);
RcppExport SEXP c_sum(SEXP);
RcppExport SEXP c_sweep(SEXP, SEXP);
RcppExport SEXP f77_hello_wrap();
RcppExport SEXP f77_primesbelow_wrap(SEXP);
RcppExport SEXP f77_sum_wrap(SEXP);
RcppExport SEXP f77_sweep_wrap(SEXP, SEXP);
RcppExport SEXP f90_hello_wrap();
RcppExport SEXP f90_primesbelow_wrap(SEXP);
RcppExport SEXP f90_sum_wrap(SEXP);
RcppExport SEXP f90_sweep_wrap(SEXP, SEXP);
RcppExport SEXP R_num_procs();

static const R_CallMethodDef CallEntries[] = {
    {"_Romp_rcpp_hello_", (DL_FUNC) &_Romp_rcpp_hello_, 0},
    {"_Romp_rcpp_sum_", (DL_FUNC) &_Romp_rcpp_sum_, 1},
    {"_Romp_rcpp_sweep_", (DL_FUNC) &_Romp_rcpp_sweep_, 2},
    {"_Romp_rcpp_primesbelow_", (DL_FUNC) &_Romp_rcpp_primesbelow_, 1},
    {"c_hello",                 (DL_FUNC) &c_hello,                 0},
    {"c_primesbelow",           (DL_FUNC) &c_primesbelow,           1},
    {"c_sum",                   (DL_FUNC) &c_sum,                   1},
    {"c_sweep",                 (DL_FUNC) &c_sweep,                 2},
    {"f77_hello_wrap",          (DL_FUNC) &f77_hello_wrap,          0},
    {"f77_primesbelow_wrap",    (DL_FUNC) &f77_primesbelow_wrap,    1},
    {"f77_sum_wrap",            (DL_FUNC) &f77_sum_wrap,            1},
    {"f77_sweep_wrap",          (DL_FUNC) &f77_sweep_wrap,          2},
    {"f90_hello_wrap",          (DL_FUNC) &f90_hello_wrap,          0},
    {"f90_primesbelow_wrap",    (DL_FUNC) &f90_primesbelow_wrap,    1},
    {"f90_sum_wrap",            (DL_FUNC) &f90_sum_wrap,            1},
    {"f90_sweep_wrap",          (DL_FUNC) &f90_sweep_wrap,          2},
    {"R_num_procs",             (DL_FUNC) &R_num_procs,             0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Romp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
