# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_ <- function() {
    invisible(.Call('_Romp_rcpp_hello_', PACKAGE = 'Romp'))
}

rcpp_sum_ <- function(x) {
    .Call('_Romp_rcpp_sum_', PACKAGE = 'Romp', x)
}

rcpp_parallel_rng_ <- function(seed) {
    invisible(.Call('_Romp_rcpp_parallel_rng_', PACKAGE = 'Romp', seed))
}

rcpp_sweep_ <- function(x, vec) {
    .Call('_Romp_rcpp_sweep_', PACKAGE = 'Romp', x, vec)
}

rcpp_primesbelow_ <- function(n) {
    .Call('_Romp_rcpp_primesbelow_', PACKAGE = 'Romp', n)
}

